in this lesson we practice numpy library.

There are two ways to create arrays numpy:
- either from an exisiting list, etc
- or using arrays

In [7]:
import numpy as np
# create an array 
x = np.array([1,23,4,5]) # must contain elements of the same datastypes
print(x)

# dtype how it is stored in memory
x.dtype # how it's stired in memory

# shape the sizes of each dimensions and their number
x.shape
#  # of rows. # of cloumn
# up casting from int like float to not lose percision

# two dimensional 
y = np.array([[1,2,3,4],[1,5,6,7],[8,9,0,5]])
print(y.shape)
print(y.size)

[ 1 23  4  5]
(3, 4)
12


In [8]:
# a string array 
x = np.array(['Hello', 'world'])
print(x.dtype)

# to specify the data gtype w ecould use attribute in the function array 
## , dtype=np.int64

<U5


In [14]:
# We can save the array into a directory file
np.save('my_arr.npy', x)

# We can load the saved array 
y = np.load('my_array.npy')

In [16]:
x = np.zeros((3,4)) # creates an array of shape (3,4) and makes them zeros
print(x)

y = np.ones((1,2)) # full of onees
print(y)

# we can use np also to create it and fill it with what we need 
z = np.full((3,4), 'h')
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]]
[['h' 'h' 'h' 'h']
 ['h' 'h' 'h' 'h']
 ['h' 'h' 'h' 'h']]


In [17]:
## in python there is identity matrix
xi = np.eye(5) # 5* 5 identity
print(xi)

## to create a diagonal matrix
xd = np.diag([10,20,30,50])
print(xd)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [19]:
# to genrate arrays with specific ragne
# args-> start , stop , step
m = np.arange(10) # stop arg from 0 to 9
print(m)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
m = np.arange(4, 10) # start arg , stop arg (exclusive)
print(m)

[4 5 6 7 8 9]


In [21]:
# step deauslt is 1 step 
m = np.arange(4, 20, 3) # stop arg from 4 to 20 evenly spaced by 3
print(m)

[ 4  7 10 13 16 19]


In [23]:
# start, stop, n
# stop and start enclusive but you can use the end point
o = np.linspace(0, 25, 10, endpoint=False)
print(o)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [26]:
o = np.arange(20)
# to make a reshape 
o = np.reshape(o, (4,5))
print(o)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
# we need to create a random vlaues in ML like using it to weights to neural networks
x = np.random.random((3,3))
print(x)

# int within spcfic interval 
x = np.random.randint(4, 15, (3,2))
print(x)


[[0.06090164 0.57084473 0.57783146]
 [0.49044925 0.05250129 0.12140406]
 [0.41392821 0.21920205 0.55193856]]
[[12  4]
 [ 9  9]
 [ 6  6]]


In [28]:
# radnom numbers that satisfies cerin statisic number

c = np.random.normal(0,0.1,size= (1000,1000))
print(c)

[[-0.01758969  0.08054603  0.02942354 ... -0.05127216  0.05191186
   0.05056932]
 [ 0.00254654  0.02339721 -0.19668825 ...  0.04671387  0.18646948
   0.02190589]
 [ 0.03974879 -0.01393804 -0.02494286 ... -0.00441695 -0.02633329
   0.0550337 ]
 ...
 [-0.00066611  0.00618206 -0.12496383 ...  0.15533552 -0.02452562
  -0.09333651]
 [ 0.1530254   0.01096207  0.08738516 ... -0.05037317 -0.07785659
   0.09231604]
 [ 0.02530726  0.10994013 -0.14762704 ...  0.08794275 -0.166015
  -0.06573497]]


In [29]:
print(c.std())

0.10007745154596909


In [31]:
print('X has dimensions:', c.shape)
print('X is an object of type:', type(c))
print('The elements in X are of type:', c.dtype)
print('The elements in X have a mean of:', c.mean())
print('The maximum value in X is:', c.max())
print('The minimum value in X is:', c.min())
print('X has', (c < 0).sum(), 'negative numbers')
print('X has', (c > 0).sum(), 'positive numbers')

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 6.113654310871596e-05
The maximum value in X is: 0.45437780370013237
The minimum value in X is: -0.47114638082979865
X has 499885 negative numbers
X has 500115 positive numbers


#### Create an ndarray
Using the NumPy functions you learned about on the previous page, create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive).

In [33]:
X = np.arange(2,34,2).reshape(4,4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


### Accessing, Deleting, and Inserting Elements Into ndarrays

In [34]:
'''Access'''
x = np.array([1,2,3,4,5])
print(x)

# from the begining of the array 
print(x[3])

# from the end of the array 
print(x[-3])

[1 2 3 4 5]
4
3


In [35]:
'''Modify'''
x[3] = 20
print(x[3])


20


In [39]:
'''Delete'''
# W = np.delete(3)

# there is also append 
# insert a row usinh insert axis=0
# insert a coulmn insert axis = 1

'Delete'

## Slicing 

In general you will come across three types of slicing:

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [ ]:
np.sort()

Arithmetic operations and Broadcasting 
arrays of diffrett shapes ( broadcastable or have the same shape) 


Use Broadcasting to create a 4 x 4 ndarray that has its first column full of `1`s, its second column full of `2`s, its third column full of `3`s, etc..

In [40]:
X = np.ones((4,4)) * np.arange(1,5)
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


 Manipulating ndarrays
 Create a 5 x 5 ndarray `X` with consecutive integers from 1 to 25 (inclusive). Afterwards use Boolean indexing to pick out only the odd numbers in the array and assign the result to `Y`.

In [43]:
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26).reshape(5,5)
print(X)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Boolean Indexing, Set Operations, and Sorting
when we don't havea small range

In [41]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [ 1  2  3 20  5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2]
The elements that are in x that are not in y: [ 1  3  5 20]
All the elements of x and y: [ 1  2  3  4  5  6  7  8 20]


In [42]:
## ndarray.sort(axis=-1, kind=None, order=None)

# Returns the sorted unique elements of an array
print(np.unique(x))

[ 1  2  3  5 20]
